Improve plug'n'playability of TS declarations
octokit/node-github pull request #1229
Opened 2019-01-29 21:31 UTC by weswigham

This declaration file uses the esnext async iterable types - if using TS >= 3.0, this comment will pull that lib in automatically.

2019-01-30 01:48 UTC, weswigham commented
Geh, older versions of TS issue an error on the directive - just keep this in mind if you update to a newer TS version.

2019-01-30 01:51 UTC, gr2m commented
Okay so updating typescript to latest version should take care of it? Can you add it to this PR?

2019-01-31 23:18 UTC, wolfy1339 requested changes

2019-01-31 23:18 UTC, wolfy1339 commented on scripts/templates/index.d.ts.tpl
>   * This declaration file requires TypeScript 2.1 or above.
```suggestion
  * This declaration file requires TypeScript 3.0 or above.
```

2019-02-01 18:13 UTC, gr2m approved these changes
Thanks everyone!

2019-02-01 18:14 UTC, merged