adding test for Issue 1497
octokit/node-github pull request #1499
Opened 2019-10-08 18:04 UTC by ram-nad

Test for issue: #1497

2019-10-08 18:10 UTC, gr2m requested changes

2019-10-08 18:10 UTC, gr2m commented on .gitignore
> +/.vscode/
Please remove that, it's unrelated to the project. You should have a global gitignore on your system that ignores the `.vscode` folder everywhere.

2019-10-08 18:10 UTC, gr2m commented on test/issues/1497-include-error-message-on-validation-error.js
> +      .reply(200, {
The response code is `403`, not `200`.

2019-10-08 18:10 UTC, gr2m commented on test/issues/1497-include-error-message-on-validation-error.js
> +    });
You still need to check that `octokit.repos.updateBranchProtection()` rejects and that the error includes the error message. You can check that `error.message` is `Validation failed: Only organization repositories can have users and team restrictions`

2019-10-08 18:13 UTC, ram-nad commented
sure sir. Thanks.

Sir does this project use prettier?

2019-10-08 19:18 UTC, ram-nad commented
Sir sorry for messing things up. I had to reset my branch. And commit changes again.

2019-10-08 22:19 UTC, gr2m reviewed
can you rename the faile to `test/issues/1497-include-error-message-on-validation-error-test.js`? Without the `-test.js` ending it will not be run by Mocha, which is why the test is currently not shown as failing

2019-10-08 22:35 UTC, ram-nad commented
sir, is my code correct or the error is expected?

2019-10-08 23:14 UTC, gr2m commented
Yes, an error is expected, you are creating a test case to reproduce the problem reporting in #1479.

But the error is not what we are looking for: https://github.com/octokit/rest.js/runs/252822246#step:7:256

It looks like the mock you defined does not match the request that is being sent. Can you look into that?

2019-10-08 23:16 UTC, ram-nad commented
yes sir i will check again

2019-10-09 00:29 UTC, ram-nad commented
Sir, I fixed the mock server. I had a question, why is accept header getting `machine-man` preview by default. Also sir i think that `application/vnd.github.v3+json` should also be added by default. Thank You.

2019-10-09 00:46 UTC, gr2m commented
> I had a question, why is accept header getting machine-man preview by default. 

We can remove that. The only relevant preview is `luke-cage`, the others can be removed

> Also sir i think that application/vnd.github.v3+json should also be added by default.

If a preview header is set, then `application/vnd.github.v3+json` doesn't need to be set, too

2019-10-09 00:49 UTC, gr2m commented
> I had a question, why is accept header getting machine-man preview by default

Oh I see, you don't set the `machine-man` preview yourself. That is very odd, it should not be set automatically, looks like a separate bug. Feel free to create a follow up issue / pull request, once we are don with this :)

The test error now says what we wanted:

```
      + expected - actual

      -Validation Failed
      +Validation failed: Only organization repositories can have users and team restrictions
```

Next up is changing the code to make the test pass. Would you like to give that a try? It's possible that it will need to be fixed in https://github.com/octokit/request.js/, I'd have to investigate myself

2019-10-09 03:44 UTC, ram-nad commented
Sure sir i would like to try. Do we need to we need to change 3 files like `@octokit/request/dist-src`, `@octokit/request/dist-node`, `@octokit/request/dist-web` ?

2019-10-09 05:29 UTC, gr2m commented
I would leave this pull request as is for now. 

Start a new pull request for https://github.com/octokit/request.js/, add a test similar to this one https://github.com/octokit/request.js/blob/0fc38c0fc0da22556fb348500b5c5844650e52e5/test/request.test.ts#L445-L484 but with the request you did in here.

`octokit.repos.updateBranchProtection(parameters)` is just an alias for `request("PUT /repos/:owner/:repo/branches/:branch/protection", parameters)`

Once we create the test and fix it in `@octokit/request`, we can update the `@octokit/request` version as part of this pull request and it the test should pass

2019-10-09 05:30 UTC, ram-nad commented
Okk sir.

2019-10-09 05:31 UTC, ram-nad commented
Sir would i use nock for mocking

2019-10-09 05:43 UTC, gr2m commented
fetchMock in https://github.com/octokit/request.js, try to follow the way the other tests are done

2019-10-09 05:49 UTC, ram-nad commented
sure sir. Sir there are certain type matching errors in the request.test.ts file. What should I do? Most of them are related to Headers type being incompatible.

2019-10-09 05:56 UTC, gr2m commented
start a PR with what you have, I'll have a look tomorrow

2019-10-09 05:56 UTC, ram-nad commented
okk thanks sir.

2019-10-11 18:38 UTC, ram-nad commented
Sir, this `error-test` is failing. Should i  update that test also?

2019-10-11 23:02 UTC, gr2m approved these changes
Perfect, thanks @ram-nad!

2019-10-11 23:03 UTC, gr2m commented
Hmm the tests are still failing, can you have a look what might be going on?

2019-10-12 04:04 UTC, ram-nad commented
Yes sir. Actually a previously written test depends upon `error.message` being `Validation failed` instead of the complete message with reasons that it is now having.

2019-10-12 04:05 UTC, gr2m commented
Can you adapt the other test?

2019-10-12 06:34 UTC, gr2m approved these changes
Thanks 👍

2019-10-12 06:35 UTC, merged