Greenkeeper/@octokit/routes 9.0.2
octokit/node-github pull request #921
Opened 2018-06-16 02:44 UTC by gr2m

closes https://github.com/octokit/rest.js/pull/914, closes https://github.com/octokit/rest.js/pull/920

ping @bitsol this PR introduces the missing methods for user migrations. Could you double check if they work for you?

2018-06-16 15:30 UTC, bitsol commented
Were there any issues with my #914 PR?
I also think #916 is a blocker for testing `octokit.migrations.getArchiveForAuthenticatedUser()`, but I'll review what I can when the time comes. 😃

2018-06-16 18:03 UTC, gr2m commented
You could try `octokit.migrations.getArchiveForAuthenticatedUser()` with a smaller archive maybe so it won’t hit the memory limit? 

#914 was great, it’s just that I most of the changes to lib/routes.json is happening automatically. All that’s needed is to add a new key to one of the scopes which will become the method name, the method and the url. Then run `npm run generate-routes` and it will add the rest automatically. So it was easier for me to do it that way. The new method names are also based on the `idName` properties from https://github.com/octokit/routes (https://github.com/octokit/routes/blob/cab6f02970cd1d953533bbd753520be7810ee558/index.json#L6626-L6765) so hopefully they won’t need to be changed again

2018-06-16 18:48 UTC, sgvictorino requested changes
All the migration routes need to include "application/vnd.github.wyandotte-preview+json" in the "Accept" header.
See how it's done with the organization migrations: https://github.com/octokit/rest.js/blob/8225347b8d99ef4908bbb7e6f5e08f458c1b48a3/lib/routes.json#L4140

2018-06-16 19:09 UTC, bitsol commented
Anyway, with #923, I've tested and can approve the changes to:

- [ ] `octokit.migrations.deleteArchiveForAuthenticatedUser()`
- [ ] `octokit.migrations.getArchiveForAuthenticatedUser()`
- [ ] `octokit.migrations.getStatusForAuthenticatedUser()`
- [ ] `octokit.migrations.listForAuthenticatedUser()`
- [x] `octokit.migrations.startForAuthenticatedUser()`
- [ ] `octokit.migrations.unlockRepoForAuthenticatedUser()`

2018-06-16 20:36 UTC, bitsol commented
I still have the same error.
Here's a little walkthrough. It doesn't show me changing the code, but the way the outputs evolve reflects that: https://asciinema.org/a/qzvJQ5VxDSwoyTTwlFEWzw2UA

2018-06-17 08:44 UTC, gr2m commented
I’ll go ahead and merge this so we get the new APIs in, here is a follow up issue for the problem with `octokit.migrations.unlockRepoForAuthenticatedUser()`: #https://github.com/octokit/rest.js/issues/925

2018-06-17 09:18 UTC, merged